[user]
name = "floriansenat"
email = "github.conductor645@passmail.net"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/github.pub"

# [git]
# sign-on-push = true

[ui]
default-command = "log"
editor = "nvim"
diff-formatter = ["difft", "--color=always", "$left", "$right"]
diff-editor = ":builtin"

[colors]
"diff removed" = "magenta"
"diff modified" = "yellow"

[merge-tools.difft]
diff-args = ["--color=always", "$left", "$right"]

[aliases]
gp = ["git", "push"]
gf = ["git", "fetch"]
nm = ["new", "main@origin"]
"bm@-" = ["bookmark", "move", "-f", "heads(::@ & bookmarks())", "-t", "@-", "-B"]
"st@" = ["log", "-r", "main@origin::@"]

[[--scope]]
--when.repositories = ["~/work"]

[--scope.user]
name = "Florian SÃ©nat"
email = "florian.senat@yousign.com"

[--scope.signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/yousign.pub"

